export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const ERR_CATEGORIES = 'ERR_CATEGORIES';

export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const CLEAR_OLD_PRODUCTS = 'CLEAR_OLD_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const ERR_PRODUCTS = 'ERR_PRODUCTS';
export const FILTER_SELECT = 'FILTER_SELECT';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const REQUEST_PRODUCT = 'REQUEST_PRODUCT';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';
export const ERR_PRODUCT = 'ERR_PRODUCT';
export const SELECT_IMAGE = 'SELECT_IMAGE';
export const CLEAR_OLD_PRODUCT = 'CLEAR_OLD_PRODUCT';

export const ADD_ITEM_CART = 'ADD_ITEM_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const CHANGE_QUANTITY_ITEM = 'CHANGE_QUANTITY_ITEM';